import { KatalogTypes } from "../Action/ActionTypes";
let KatalogData = {
  katalogdata: [
    {
      id: 1,
      img: "./catalogGOODS/perforator.png",
      count:1,
      nomi: "Перфоратор универсальный Wander X645-46 GF 1450W",
      narxi: 15999,
      skidka: "15",
      like: false,
      catalogs: "katalogdata",
    },
    {
      id: 2,
      img: "./catalogGOODS/bolgarka2.png",
      count:1,
      nomi: "Смеситель Faris G-120 для раковины",
      narxi: 1789,
      skidka: null,
      like: false,
      catalogs: "katalogdata",
    },
    {
      id: 3,
      img: "./catalogGOODS/circular_pila_bosch.png",
      count:1,
      nomi: "Триммерная леска «Спираль-100»",
      narxi: 312,
      skidka: 10,
      like: false,
      catalogs: "katalogdata",
    },
    {
      id: 4,
      img: "./catalogGOODS/shlifovka.png",
      count:1,
      nomi: "Унитаз подвесной Aragio с двойным сливом",
      narxi: 15999,
      skidka: 12,
      like: false,
      catalogs: "katalogdata",
    },
    {
      id: 5,
      img: "./catalogGOODS/nabor.png",
      count:1,
      nomi: "Набор гравировальных насадок Nozzle-Tok",
      narxi: 15999,
      skidka: 15,
      like: false,
      catalogs: "katalogdata",
    },
    {
      id: 6,
      img: "./catalogGOODS/circular_pila_zubr.png",
      count:1,
      nomi: "Набор гравировальных насадок Nozzle-Tok",
      narxi: 15999,
      skidka: 15,
      like: false,
      catalogs: "katalogdata",
    },
    {
      id: 7,
      img: "./catalogGOODS/bolgarka2.png",
      count:1,
      nomi: "Смеситель Faris G-120 для раковины",
      narxi: 1789,
      skidka: null,
      like: false,
      catalogs: "katalogdata",
    },
    {
      id: 8,
      img: "./catalogGOODS/drell_makita_s_ruchkoy.png",
      count:1,
      nomi: "Триммерная леска «Спираль-100»",
      narxi: 312,
      skidka: 10,
      like: false,
      catalogs: "katalogdata",
    },
    {
      id: 9,
      img: "./catalogGOODS/betonomeshalka.png",
      count:1,
      nomi: "Набор гравировальных насадок Nozzle-Tok",
      narxi: 15999,
      skidka: 15,
      like: false,
      catalogs: "katalogdata",
    },
    {
      id: 10,
      img: "./catalogGOODS/perforator_bosch.png",
      count:1,
      nomi: "Унитаз подвесной Aragio с двойным сливом",
      narxi: 15999,
      skidka: 12,
      like: false,
      catalogs: "katalogdata",
    },
    {
      id: 11,
      img: "./catalogGOODS/constr_mixer.png",
      count:1,
      nomi: "Перфоратор универсальный Wander X645-46 GF 1450W",
      narxi: 15999,
      skidka: 15,
      like: false,
      catalogs: "katalogdata",
    },
    {
      id: 12,
      img: "./catalogGOODS/drell_makita_bez_ruchki.png",
      count:1,
      nomi: "Набор гравировальных насадок Nozzle-Tok",
      narxi: 15999,
      skidka: 15,
      like: false,
      catalogs: "katalogdata",
    },
    {
      id: 13,
      img: "./catalogGOODS/bolgarka_makita.png",
      count:1,
      nomi: "Смеситель Faris G-120 для раковины",
      narxi: 1789,
      skidka: null,
      like: false,
      catalogs: "katalogdata",
    },
    {
      id: 14,
      img: "./catalogGOODS/shlifovka_zubr.png",
      count:1,
      nomi: "Триммерная леска «Спираль-100»",
      narxi: 312,
      skidka: 10,
      like: false,
      catalogs: "katalogdata",
    },
    {
      id: 15,
      img: "./catalogGOODS/lobzik_makita.png",
      count:1,
      nomi: "Унитаз подвесной Aragio с двойным сливом",
      narxi: 15999,
      skidka: 12,
      like: false,
      catalogs: "katalogdata",
    },
    {
      id: 16,
      img: "./catalogGOODS/shlifovka_makita.png",
      count:1,
      nomi: "Перфоратор универсальный Wander X645-46 GF 1450W",
      narxi: 15999,
      skidka: 15,
      like: false,
      catalogs: "katalogdata",
    },
    {
      id: 17,
      img: "./catalogGOODS/stroy_fen_zubr.png",
      count:1,
      nomi: "Триммерная леска «Спираль-100»",
      narxi: 312,
      skidka: 10,
      like: false,
      catalogs: "katalogdata",
    },
    {
      id: 18,
      img: "./catalogGOODS/graver_zubr.png",
      count:1,
      nomi: "Набор гравировальных насадок Nozzle-Tok",
      narxi: 15999,
      skidka: 15,
      like: false,
      catalogs: "katalogdata",
    },
    {
      id: 19,
      img: "./catalogGOODS/drell_makita_bez_ruchki_2.png",
      count:1,
      nomi: " Унитаз подвесной Aragio с двойным сливом",
      narxi: 15999,
      skidka: 15,
      like: false,
      catalogs: "katalogdata",
    },
    {
      id: 20,
      img: "./catalogGOODS/perforator_bosch_siniy.png",
      count:1,
      nomi: "Смеситель Faris G-120 для раковины",
      narxi: 1789,
      skidka: null,
      like: false,
      catalogs: "katalogdata",
    },
    {
      id: 21,
      img: "./catalogGOODS/drell_PIT.png",
      count:1,
      nomi: "Перфоратор универсальный Wander X645-46 GF 1450W",
      narxi: 15999,
      skidka: 15,
      like: false,
      catalogs: "katalogdata",
    },
    {
      id: 22,
      img: "./catalogGOODS/perforator_zubr.png",
      count:1,
      nomi: "Унитаз подвесной Aragio с двойным сливом",
      narxi: 15999,
      skidka: 12,
      like: false,
      catalogs: "katalogdata",
    },
    {
      id: 23,
      img: "./catalogGOODS/stanok_vixr.png",
      count:1,
      nomi: "Перфоратор универсальный Wander X645-46 GF 1450W",
      narxi: 15999,
      skidka: 12,
      like: false,
      catalogs: "katalogdata",
    },
    {
      id: 24,
      img: "./catalogGOODS/rubanok_vixr.png",
      count:1,
      nomi: "Перфоратор универсальный Wander X645-46 GF 1450W",
      narxi: 15999,
      skidka: 12,
      like: false,
      catalogs: "katalogdata",
    },
    {
      id: 25,
      img: "./catalogGOODS/perforator_PIT.png",
      count:1,
      nomi: "Триммерная леска «Спираль-100»",
      narxi: 312,
      skidka: 10,
      like: false,
      catalogs: "katalogdata",
    },
    {
      id: 26,
      img: "./catalogGOODS/kley_pistolet_stayer.png",
      count:1,
      nomi: "Триммерная леска «Спираль-100»",
      narxi: 15999,
      skidka: 15,
      like: false,
      catalogs: "katalogdata",
    },
    {
      id: 27,
      img: "./catalogGOODS/nabor.png",
      count:1,
      nomi: "Набор гравировальных насадок Nozzle-Tok",
      narxi: 15999,
      skidka: 15,
      like: false,
      catalogs: "katalogdata",
    },
    {
      id: 28,
      img: "./catalogGOODS/rubanok_makita.png",
      count:1,
      nomi: "Смеситель Faris G-120 для раковины",
      narxi: 1789,
      skidka: null,
      like: false,
      catalogs: "katalogdata",
    },
    {
      id: 29,
      img: "./catalogGOODS/pilesos_zubr.png",
      count:1,
      nomi: "Смеситель Faris G-120 для раковины",
      narxi: 1789,
      skidka: null,
      like: false,
    },
    {
      id: 30,
      img: "./catalogGOODS/drell_makita_bez_ruchki_2.png",
      count:1,
      nomi: "Унитаз подвесной Aragio с двойным сливом",
      narxi: 15999,
      skidka: 12,
      like: false,
    },
    {
      id: 31,
      img: "./catalogGOODS/bolgarka1.png",
      count:1,
      nomi: "Унитаз подвесной Aragio с двойным сливом",
      narxi: 15999,
      skidka: 12,
      like: false,
    },
    {
      id: 32,
      img: "./catalogGOODS/nabor.png",
      count:1,
      nomi: "Набор гравировальных насадок Nozzle-Tok",
      narxi: 15999,
      skidka: 15,
      like: false,
      catalogs: "katalogdata",
    },
  ],
  tiptavarData: [
    {
      title: "Набор",
      bool: false,
      catalog: "tiptavarData",
    },
    {
      title: "Стойка",
      bool: false,
      catalog: "tiptavarData",
    },
    {
      title: "Адаптер",
      bool: false,
      catalog: "tiptavarData",
    },
    {
      title: "Держатель",
      bool: false,
      catalog: "tiptavarData",
    },
    {
      title: "Фильтр",
      bool: false,
      catalog: "tiptavarData",
    },
    {
      title: "Инструмент",
      bool: false,
      catalog: "tiptavarData",
    },
  ],
  brendData: [
    {
      title: "STAYER",
      bool: false,
      catalog: "brendData",
    },
    {
      title: "HOMEPROFEE",
      bool: false,
      catalog: "brendData",
    },
    {
      title: "PECAHTA",
      bool: false,
      catalog: "brendData",
    },
    {
      title: "MAKITA",
      bool: false,
      catalog: "brendData",
    },
    {
      title: "HUNTER",
      bool: false,
      catalog: "brendData",
    },
  ],
  materialData: [
    {
      title: "Латунь",
      bool: false,
      catalog: "materialData",
    },
    {
      title: "Медь",
      bool: false,
      catalog: "materialData",
    },
    {
      title: "Металл",
      bool: false,
      catalog: "materialData",
    },
    {
      title: "Металл, пластик",
      bool: false,
      catalog: "materialData",
    },
    {
      title: "Бумага",
      bool: false,
      catalog: "materialData",
    },
  ],
  korzinka: [],
  categorya: [],
};
export default function KatalogRed(state = KatalogData, { type, payload }) {
  switch (type) {
    case KatalogTypes.katalogs:
      state = { ...state, katalogOpens: !state.katalogOpens };
      return state;
    case KatalogTypes.katalogs2:
      state = { ...state, katalogOpens2: !state.katalogOpens2 };
      return state;
    case KatalogTypes.katalogs3:
      state = { ...state, katalogOpens3: !state.katalogOpens3 };
      return state;
      case KatalogTypes.katalogs4:
      state = { ...state, katalogOpens4: !state.katalogOpens4 };
      return state;
    case KatalogTypes.chekced:
      state = {
        ...state,
        [payload.catalog]: state?.[payload.catalog].map((elem) =>
          elem.title === payload.title ? { ...elem, bool: !elem.bool } : elem
        ),
      };
      return state;
    case KatalogTypes.likes:
      state = {
        ...state,
        katalogdata: state?.katalogdata?.map((elem) =>
          elem.id === payload.id ? { ...elem, like: !elem.like } : elem
        ),
      };
      return state;
    default:
      return state;
  }
}
